name: tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest tests/test*
